version: "3.7"
services:


  policy-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    networks:
      - envoymesh
    ports:
      - "8085:8000"
    # depends_on:
    #   - postgresserver

  ext_authz-opa-service:
    image: openpolicyagent/opa:0.25.1-istio
    environment:
      - VALID_ISSUERS=http://keycloak:8080/auth/realms/master
      - VALID_AUDIENCE=client1
    ports:
      - "9191:9191"
      - "8282:8282"
      - "8181:8181"
    volumes:
      - ./config/opa-service/policy.rego:/etc/policy.rego
      - ./config/opa-service/opa.yaml:/opa.yaml
    command:
      - run
      - --log-level=debug
      - --server
      - --config-file=/opa.yaml
      - --log-format=json-pretty
      - --diagnostic-addr=0.0.0.0:8282
      - --set=plugins.envoy_ext_authz_grpc.addr=:9002
      - --set=decision_logs.console=true
    networks:
      - envoymesh

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - envoymesh

  # postgresserver:
  #   image: postgres:14
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=api
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=policyapi
  #   networks:
  #     - envoymesh

  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - envoymesh

  upstream-service:
    image: fiware/orion:${ORION_VERSION:-3.3.1}
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -noCache -dbhost mongo
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - envoymesh

volumes:
  mongodata:

networks:
  envoymesh: {}
